FROM resin/%%RESIN_MACHINE_NAME%%-node:slim

WORKDIR /usr/src/app
ENV INITSYSTEM=off

COPY package*json ./
RUN npm install --only=production --unsafe-perms

COPY index.js ./
COPY start.sh ./

CMD ["bash", "start.sh"]
